CREATE DATABASE riachovelho;

-- Tabela de Produtos
CREATE TABLE riachovelho.PRODUTOS (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PRECO DECIMAL(10, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL
);

-- Tabela de Clientes
CREATE TABLE riachovelho.CLIENTES (
    IDCLIENTES INT PRIMARY KEY AUTO_INCREMENT,
    PRIMEIRO_NOME VARCHAR(50) NOT NULL,
    SEGUNDO_NOME VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    TELEFONE VARCHAR(20)
);

-- Tabela de Vendas
CREATE TABLE riachovelho.VENDAS (
    IDVENDAS INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTES INT,
    DATA_VENDA DATE NOT NULL,
    MONTANTE_TOTAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (IDCLIENTES) REFERENCES CLIENTES(IDCLIENTES)
);

-- Tabela de Itens Vendidos
CREATE TABLE riachovelho.ITENS_VENDIDOS (
    IDITEM_VENDIDO INT PRIMARY KEY AUTO_INCREMENT,
    IDVENDAS INT,
    IDPRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (IDVENDAS) REFERENCES VENDAS(IDVENDAS),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTOS(IDPRODUTO)
);

-- Tabela de Funcionários
CREATE TABLE riachovelho.FUNCIONARIOS (
    IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    PRIMEIRO_NOME VARCHAR(50) NOT NULL, 
    SEGUNDO_NOME VARCHAR(50) NOT NULL,
    CARGO VARCHAR(100),
    DATA_CONTRATADO DATE
);
INSERT INTO CLIENTES (PRIMEIRO_NOME, SEGUNDO_NOME, email, TELEFONE) VALUES
('João', 'Silva', 'joao.silva@email.com', '1234567890'),
('Maria', 'Santos', 'maria.santos@email.com', '0987654321'),
('Pedro', 'Ferreira', 'pedro.ferreira@email.com', '1112223333'),
('Ana', 'Oliveira', 'ana.oliveira@email.com', '5556667777');

INSERT INTO FUNCIONARIOS (PRIMEIRO_NOME, SEGUNDO_NOME, CARGO, DATA_CONTRATADO) VALUES
('José', 'Silva', 'Vendedor', '2022-01-15'),
('Ana', 'Santos', 'Gerente de Vendas', '2021-09-20'),
('Mariana', 'Ferreira', 'Caixa', '2023-03-10'),
('Carlos', 'Oliveira', 'Estoquista', '2022-11-05');

INSERT INTO PRODUTOS (NOME, DESCRIPTION, PRECO, QUANTIDADE_ESTOQUE) VALUES
('Camiseta', 'Camiseta branca de algodão', 25.00, 100),
('Calça Jeans', 'Calça jeans azul masculina', 50.00, 50),
('Vestido', 'Vestido floral de verão', 45.00, 75),
('Sapato', 'Sapato social preto', 60.00, 30);

INSERT INTO VENDAS (IDCLIENTES, DATA_VENDA, MONTANTE_TOTAL) VALUES
(1, '2024-04-25', 150.00),
(2, '2024-04-26', 85.00),
(3, '2024-04-27', 120.00),
(4, '2024-04-28', 90.00);

INSERT INTO ITENS_VENDIDOS (IDVENDAS, IDPRODUTO, QUANTIDADE, PRECO) VALUES
(1, 1, 6, 1),
(2, 1, 1, 2),
(3, 2, 3, 1),
(4, 1, 4, 2);
